# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-30 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170530_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
