# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170531_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(max_length=20),
        ),
    ]
